# Generated by Django 3.2.6 on 2021-08-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_estoque')),
                ('id_produto', models.IntegerField(verbose_name='id_produto')),
                ('quantidade', models.IntegerField(verbose_name='quantidade')),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
